"""Constant values for emu mbus integration."""

DOMAIN = "emu_m_bus_center"


ACTIVE_ENERGY_TARIFF_1 = "active_energy_tariff_1"
ACTIVE_ENERGY_TARIFF_2 = "active_energy_tariff_2"
ACTIVE_POWER_PHASE_1 = "active_power_phase_1"
ACTIVE_POWER_PHASE_2 = "active_power_phase_2"
ACTIVE_POWER_PHASE_3 = "active_power_phase_3"
ACTIVE_POWER_ALL_PHASES = "active_power_all_phases"
VOLTAGE_PHASE_1 = "voltage_phase_1"
VOLTAGE_PHASE_2 = "voltage_phase_2"
VOLTAGE_PHASE_3 = "voltage_phase_3"
CURRENT_PHASE_1 = "current_phase_1"
CURRENT_PHASE_2 = "current_phase_2"
CURRENT_PHASE_3 = "current_phase_3"
CURRENT_ALL_PHASES = "current_all_phases"
FREQUENCY = "frequency"
RESET_COUNTER = "reset_counter"
CURRENT_TRANSFORMER_FACTOR = "current_transformer_factor"
ERROR_FLAGS = "error_flags"
