"""Constant values for emu mbus integration."""

DOMAIN = "emu_m_bus_center"


ACTIVE_ENERGY_TARIFF_1 = "Active Energy Tariff 1"
ACTIVE_ENERGY_TARIFF_2 = "Active Energy Tariff 2"
ACTIVE_POWER_PHASE_1 = "Active Power Phase 1"
ACTIVE_POWER_PHASE_2 = "Active Power Phase 2"
ACTIVE_POWER_PHASE_3 = "Active Power Phase 3"
ACTIVE_POWER_ALL_PHASES = "Active Power All Phases"
VOLTAGE_PHASE_1 = "Voltage Phase 1"
VOLTAGE_PHASE_2 = "Voltage Phase 2"
VOLTAGE_PHASE_3 = "Voltage Phase 3"
CURRENT_PHASE_1 = "Current Phase 1"
CURRENT_PHASE_2 = "Current Phase 2"
CURRENT_PHASE_3 = "Current Phase 3"
CURRENT_ALL_PHASES = "Current All Phases"
FREQUENCY = "Frequency"
RESET_COUNTER = "Reset Counter"
CURRENT_TRANSFORMER_FACTOR = "Current Transformer Factor"
ERROR_FLAGS = "Error Flags"
SERIAL_NO = "Serial No"
