name: Validate HACS
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: HACS Action
        uses: hacs/action@main
        with:
          CATEGORY: integration
